#!/usr/bin/env python3
"""Regenerate _index/ MOCs and sync frontmatter `links:` from body [[wikilinks]].

Run via _system/scripts/reindex.sh.
"""

from __future__ import annotations

import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml

from mictlan.paths import VAULT
INDEX = VAULT / "_index"
WIKILINK_RE = re.compile(r"\[\[([^\]|#]+?)(?:\|[^\]]+)?\]\]")
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.DOTALL)
VALID_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
# Fenced code blocks and inline code spans hold wikilink *examples*, not real
# links. Mask them before extraction so docs don't leak into frontmatter links:.
# Keep in sync with brain_mcp.vault.strip_code.
FENCED_CODE_RE = re.compile(r"^[ \t]*(`{3,}|~{3,}).*?^[ \t]*\1[ \t]*$", re.DOTALL | re.MULTILINE)
INLINE_CODE_RE = re.compile(r"(`+)(?:.+?)\1")


def strip_code(text: str) -> str:
    """Blank out fenced code blocks and inline code spans."""
    text = FENCED_CODE_RE.sub(" ", text)
    text = INLINE_CODE_RE.sub(" ", text)
    return text

MOC_HEADER = "<!-- generated by _system/scripts/reindex.sh — do not hand-edit -->\n"


def load_note(path: Path) -> tuple[dict, str] | None:
    text = path.read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None
    try:
        fm = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return None
    return fm, m.group(2)


def write_note(path: Path, fm: dict, body: str) -> None:
    new = f"---\n{yaml.safe_dump(fm, sort_keys=False, allow_unicode=True).strip()}\n---\n{body}"
    if path.read_text(encoding="utf-8") != new:
        path.write_text(new, encoding="utf-8")


def all_notes() -> list[Path]:
    out: list[Path] = []
    for folder in ("notes", "meetings", "daily", "conversations"):
        d = VAULT / folder
        if d.exists():
            out.extend(sorted(d.glob("*.md")))
    return out


def sync_links() -> dict[str, set[str]]:
    """Update frontmatter `links:` from body wikilinks. Return id -> set(outgoing)."""
    outgoing: dict[str, set[str]] = {}
    for p in all_notes():
        loaded = load_note(p)
        if not loaded:
            continue
        fm, body = loaded
        scannable = strip_code(body)
        self_id = fm.get("id", p.stem)
        wikilinks = list(dict.fromkeys(
            m.group(1).strip() for m in WIKILINK_RE.finditer(scannable)
            if VALID_SLUG_RE.match(m.group(1).strip())
            and m.group(1).strip() != self_id
        ))
        if fm.get("links") != wikilinks:
            fm["links"] = wikilinks
            write_note(p, fm, body)
        outgoing[fm.get("id", p.stem)] = set(wikilinks)
    return outgoing


def collect() -> list[dict]:
    notes: list[dict] = []
    for p in all_notes():
        loaded = load_note(p)
        if not loaded:
            continue
        fm, _ = loaded
        fm["_path"] = str(p.relative_to(VAULT))
        fm.setdefault("id", p.stem)
        notes.append(fm)
    return notes


def render_people(notes: list[dict]) -> str:
    rows = [n for n in notes if n.get("type") == "person"]
    if not rows:
        return MOC_HEADER + "# People\n\n_No entries yet._\n"
    by_status: dict[str, list[dict]] = defaultdict(list)
    for n in rows:
        by_status[n.get("status", "active")].append(n)
    out = [MOC_HEADER, "# People\n"]
    for status in ("active", "dormant", "archived"):
        bucket = sorted(by_status.get(status, []), key=lambda n: n["id"])
        if not bucket:
            continue
        out.append(f"\n## {status.title()} ({len(bucket)})\n")
        out.append("| Name | Org | Role | Last contact |")
        out.append("|---|---|---|---|")
        for n in bucket:
            aliases = n.get("aliases") or []
            name = (aliases[0] if aliases else None) or n["id"].replace("-", " ").title()
            out.append(f"| [[{n['id']}|{name}]] | {n.get('org') or ''} | {n.get('role') or ''} | {n.get('last_contact') or ''} |")
    return "\n".join(out) + "\n"


def render_projects(notes: list[dict]) -> str:
    rows = [n for n in notes if n.get("type") == "project"]
    if not rows:
        return MOC_HEADER + "# Projects\n\n_No entries yet._\n"
    by_status: dict[str, list[dict]] = defaultdict(list)
    for n in rows:
        by_status[n.get("status", "active")].append(n)
    out = [MOC_HEADER, "# Projects\n"]
    for status in ("active", "dormant", "archived"):
        if status not in by_status:
            continue
        out.append(f"\n## {status.title()}\n")
        for n in sorted(by_status[status], key=lambda x: str(x.get("start") or ""), reverse=True):
            org = n.get("org") or ""
            start = n.get("start") or ""
            end = n.get("end") or "ongoing"
            out.append(f"- [[{n['id']}]] — {org} ({start} → {end})")
    return "\n".join(out) + "\n"


def render_topics(notes: list[dict]) -> str:
    rows = sorted([n for n in notes if n.get("type") in ("topic", "ref")], key=lambda n: n["id"])
    if not rows:
        return MOC_HEADER + "# Topics & references\n\n_No entries yet._\n"
    lines = [MOC_HEADER, "# Topics & references\n"]
    by_type: dict[str, list[dict]] = defaultdict(list)
    for n in rows:
        by_type[n["type"]].append(n)
    for t in ("topic", "ref"):
        if t not in by_type:
            continue
        lines.append(f"\n## {t.title()}s\n")
        for n in by_type[t]:
            tags = " ".join(f"`{x}`" for x in n.get("tags", []))
            lines.append(f"- [[{n['id']}]] {tags}")
    return "\n".join(lines) + "\n"


def render_timeline(notes: list[dict]) -> str:
    rows = [n for n in notes if n.get("type") in ("meeting", "daily", "conversation")]
    if not rows:
        return MOC_HEADER + "# Timeline\n\n_No entries yet._\n"
    rows.sort(key=lambda n: str(n.get("created") or ""), reverse=True)
    lines = [MOC_HEADER, "# Timeline\n"]
    current_month = None
    for n in rows:
        d = str(n.get("created") or "")
        month = d[:7] if d else "unknown"
        if month != current_month:
            lines.append(f"\n## {month}\n")
            current_month = month
        lines.append(f"- {d} [[{n['id']}]] _{n['type']}_")
    return "\n".join(lines) + "\n"


def render_tags(notes: list[dict]) -> str:
    counter: Counter[str] = Counter()
    files_by_tag: dict[str, list[str]] = defaultdict(list)
    for n in notes:
        for t in n.get("tags", []) or []:
            counter[t] += 1
            files_by_tag[t].append(n["id"])
    if not counter:
        return MOC_HEADER + "# Tags\n\n_No entries yet._\n"
    lines = [MOC_HEADER, "# Tags\n", "| Tag | Count | Files |", "|---|---|---|"]
    for tag, count in sorted(counter.items()):
        examples = ", ".join(f"[[{x}]]" for x in files_by_tag[tag][:5])
        lines.append(f"| `{tag}` | {count} | {examples} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    sync_links()
    notes = collect()
    (INDEX / "people.md").write_text(render_people(notes), encoding="utf-8")
    (INDEX / "projects.md").write_text(render_projects(notes), encoding="utf-8")
    (INDEX / "topics.md").write_text(render_topics(notes), encoding="utf-8")
    (INDEX / "timeline.md").write_text(render_timeline(notes), encoding="utf-8")
    (INDEX / "tags.md").write_text(render_tags(notes), encoding="utf-8")
    print(f"reindexed {len(notes)} notes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
